### ISSUE TITLE
Add Apple Silicon Support

### ISSUE THREAD

**Issue by cerpow** [cerpow/catapult#12]
Support for M1 powered macs

**Comment by mrkai77** [comment]
I tried building this app with [this comment](https://github.com/electron-userland/electron-builder/issues/5689#issuecomment-792876001) and successfully built `x64`, `arm64`, and `universal` binaries. Might be worth adding the `universal` option into `package.json`!

**Comment by cerpow** [comment]
Hey @MrKai77 ,
That is awesome! Do you have an Apple Silicon mac to test if it works?

**Comment by mrkai77** [comment]
Yes! The `arm64` binary works exactly like the `x64` version!

**Comment by cerpow** [comment]
Nice! Can you a pull request and i upload the `arm64` version to releases. But We still need to fix the update checker to download the correct file. Tanks for trying it out!

**Comment by cerpow** [comment]
Can you also look and test that? I still don't have an arm64 mac :( Much appreciated! @MrKai77

**Comment by cerpow** [comment]
@MrKai77 I fixed the updater btw and built new dmg files.

**Comment by mrkai77** [comment]
awesome!
