### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by cerpow** [cerpow/catapult#13]
Just found an issue: when i have multiple Mac Desktop opened and i click the catapult icon, it opens the windows in the desktop where i launched the app which.

By mawdld

**Comment by MatzeKitt** [comment]
The same applies to multiple virtual desktops. Do you think this is the same issue or should I create a new issue for that?

**Comment by cerpow** [comment]
I think it’s the same issue, I just haven’t tested it with multiple displays

**Comment by cerpow** [comment]
Actually it was working with multiple displays, just not multiple virtual desktops. 
I fixed both and will be included in an update.
