### ISSUE TITLE
pixroad.com Menu Item

### ISSUE THREAD

**Issue by alexlewer** [cerpow/catapult#3]
Clicking on the _pixroad.com_ menu item results in a 'Failed to Open Project' error:

![CleanShot 2020-06-23 at 15 10 34@2x](https://user-images.githubusercontent.com/1900297/85414190-b453c500-b563-11ea-9211-651e09631487.png)

**Comment by cerpow** [comment]
Yes, I'm aware of this error. I just plan to rebuild the app from the ground up since it's a bit dated and pretty hard to update. The app still works on macOS Big Sur. Thanks Alex!
